### ISSUE TITLE
Ignore folders to optimise

### ISSUE THREAD

**Issue by niclimcy** [dc7290/next-export-optimize-images#1076]
All image files in the public folder are being optimised, however, favicons do not have to be optimised.

**Describe the solution you'd like**
An option to disable optimisation for a specific file path.

**Comment by dc7290** [comment]
It would be nice to have an option to set a path to skip image optimization!

**Comment by CEM-Christian** [comment]
Recently ran into the same issue. Could the Next Image `localPatterns` option be used?

https://nextjs.org/docs/app/api-reference/components/image#localpatterns

**Comment by dc7290** [comment]
@CEM-Christian 
`localPatters` is not currently supported.
However, we are considering a way to ignore optimization in some way.
Since `localPatters` is thought to be a function for Next.js's default optimization, we are considering a way to describe it in `export-images.config.js`.

**Comment by niclimcy** [comment]
Does this only work for specific files? I tried it on a directory but images in it are still getting optimized.
