### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Prushka** [dc7290/next-export-optimize-images#1086]
**Describe the bug**

```
[Error: ENOENT: no such file or directory, open '/project-path/image.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/project-path/image.jpg'
}
```

`next-export-optimize-images` fails to run.

**/project-path/public/image.jpg** should be the correct path of the image.

I can't figure out why it's omitting the public folder in the path.

Importing and not importing `image.jpg` yield the same error message.

This means not having `image.jpg` inside any component gives the same error when it tries to optimize all images in the public folder: `- Collect images in public directory -`.

Next.js: 14.2.16, app router

**Comment by dc7290** [comment]
Can you give an example using a reproducible CodeSandbox or something similar?
As far as I've tried, I haven't been able to reproduce it.

**Comment by Emiliano-Bucci** [comment]
@dc7290 Hi! I've made a small reproduction of the error (or similar) of this topic:

[Here](https://codesandbox.io/p/devbox/vibrant-lucy-vztj9q?file=%2Fexport-imagesconfig.js%3A9%2C1&workspaceId=d27042b1-b7ba-4964-9991-754a43f7ac28)

If you run npm run build you'll see the error. Thanks!

**Comment by dc7290** [comment]
@Prushka Thanks for posting the issue!

@Emiliano-Bucci Thanks for the reproduction code! I've found the cause of the problem, so I'll fix it!
