### ISSUE TITLE
Unable to optimize images if `experimental.images.unoptimized` is true

### ISSUE THREAD

**Issue by samuelpetroline** [dc7290/next-export-optimize-images#129]
**Describe the bug**
If [`experimental.images.unoptimized`](https://nextjs.org/docs/api-reference/next/image#unoptimized) is true, the `custom-optimized-images.nd.json` file is not generated and, therefore, an error is thrown when trying to resolve the manifest path:

![image](https://user-images.githubusercontent.com/22039767/177197463-167951b6-2813-493f-aac3-ff6e7075e306.png)

**To Reproduce**
1. Add `experimental.images.unoptimized` to any `next.config`
2. Execute the build scripts
3. See error (logged as "unexpected error")

**Expected behavior**
Two options:
1. The library should warn the user about this invalid option
2. The library should override this config

**Screenshots**
See above

**Comment by dc7290** [comment]
🎉 This issue is included in version v1.5.3.
