### ISSUE TITLE
Monorepo構成にしている場合にエラーになる

### ISSUE THREAD

**Issue by daizaburou** [dc7290/next-export-optimize-images#142]
日本語ですみません。。

**Describe the bug**
yarnでworkspaceを利用して、Monorepo構成にしている場合にエラーになってしまいます。

**To Reproduce**
1. yarnでworkspaceを利用してworkspaceに`package1`、`package2`を追加（依存packageは`monorepo/node_modules`配下で管理される）
2. `package1`のみでNext.jsを使用するため、`package1`配下にnext.config.js、export-images.config.jsを配置
3. `next build && next export && next-export-optimize-images`を実行
4. 以下のエラーが出る
```
warn  - ../node_modules/next-export-optimize-images/dist/utils/getConfig.js
Module not found: Can't resolve 'next-export-optimize-images/export-images.config.js' in '/Users/monorepo/node_modules/next-export-optimize-images/dist/utils'
```

**Desktop (please complete the following information):**
- node version 18.3.0
- macOS Big Sur 11.2.3
- Next.js version 12.2.0
- next-export-optimize-images version 1.5.3

**Expected behavior**
原因としては、copyConfig.jsの書き出し先のパスと、getConfig.jsの読み込み先のパスに相違があることが考えられます。
copyConfig.jsは`monorepo/package1/node_modules/next-export-optimize-images/export-images.config.js`を作成し、
getConfig.jsは`monorepo/node_modules/next-export-optimize-images/export-images.config.js`を読みに行っているようです。

next.config.jsがある階層のnode_modulesのパスをgetConfigで読んで欲しいです。

構成のイメージは下記です。
```sh
monorepo
├── package1
│   ├── node_modules
│   │    └── next-export-optimize-images
│   │        └── export-images.config.js # ここに書き出される
│   ├── next.config.js
│   ├── export-images.config.js
│   └── package.json
├── package2
│   └── ...
├── package.json
└── node_modules
     └── next-export-optimize-images
          ├── bin
          ├── dist
          └── ...
```

**Comment by dc7290** [comment]
@daizaburou 
返信が遅くなり申し訳ありません！

monorepoプロジェクトでの使用を想定していなく、、、
どういう仕様にするのがいいか、もう少し調査するためお時間をください。

また、コントリビュートも歓迎しているため、いい案があればぜひお願いします！

**Comment by dc7290** [comment]
@daizaburou 

お待たせしました！
ルートにNext.jsプロジェクトがない、いわゆるmonorepoパターンでもこのライブラリを使用できるように変更しました。
使用にあたって特段設定するべき項目はないので、そのままお使いいただけると思います。

次のリリースで公開となります。

**Comment by dc7290** [comment]
一応自分の環境でTurborepoを使ったmonorepoはテスト済みですが、
他のツールを使った場合は動作が異なる可能性もございます。
その際はまた、Issueを新たに発行いただけると幸いです。

**Comment by dc7290** [comment]
🎉 This issue is included in version v1.6.0.

**Comment by daizaburou** [comment]
@dc7290 
ご返事遅くなりました。

迅速にご対応いただきありがとうございます！
自分の環境でも、想定通りに動くのを確認しました。

大変助かりました。
もし他になにかあったらIssue発行させていただきます。
プルリクも頑張って出せればと思います。
ありがとうございました！！

**Comment by dc7290** [comment]
@daizaburou 
うまくいったようで何よりです！！！

ぜひぜひ〜
