### ISSUE TITLE
No images were found to optimize although I use Image-component in code

### ISSUE THREAD

**Issue by wytzejan** [dc7290/next-export-optimize-images#224]
First of all thank you for your work on this. It is exactly what I need in my Next.js project in combination with a headless cms. Unfortunately I do have an issue I cannot resolve. I hope you can help me.

**Describe the bug**
Although I use the Image component from next/image in my code I keep getting the 'No images were found to optimize. (Maybe you never used the image component.)' console log during next export. I noticed that there is also no file custom-optimized-images.nd.json in my .next folder. I suppose this is generated during next build.

**To Reproduce**
1. Use Image component in the code
2. Build the app via next build (or `BASE_PATH=staging npx env-cmd -f ./environments/.env.staging next build` in my case)
3. Export the app via next export and optimize image via `next export && next-export-optimize-images`
4. Console log shows `No images were found to optimize. (Maybe you never used the image component.)`
![image](https://user-images.githubusercontent.com/10392890/188603421-e7632cc5-9f16-4b2d-b912-eba37e399f0f.png)

**Expected behavior**
Find Image components and optimize used images from code.

**Additional context**
I use the Image component like this:
![image](https://user-images.githubusercontent.com/10392890/188603900-fdde1818-72f8-44a1-8f31-6f574a070e38.png)
The source of the image is an external url directly from the cms.

The first time I did a local build and export, I saw the external images were downloaded but after that I only see the above notification.

**Comment by dc7290** [comment]
@wytzejan 

Is it possible to create a simple demo?
As much as possible I would like to solve your problem.

**Comment by samuel-2018** [comment]
@wytzejan

I also ran into the situation of getting that message after it had been working initially. 

The solution for me was to switch from importing the Image component from  'next/future/image' to importing it from 'next/image'.

(I know you said you are using 'next/image', but it could be worth double checking.)

When it wasn’t working for me, Chrome dev tools showed, under the Network tab, that the image Request URL was something like: 

`https://example.com/_next/image?url=myCMSwebsiteaddress.com%2Fuploads%2Fimagenamehere.png`

But when it is working correctly with this package, it should be something like:

`https://example.com/_next/static/chunks/images/uploads/imagenamehere.png`

@dc7290

Thanks for your work on next-export-optimize-images!

Is it possible to use this package with 'next/future/image'? Is there any different configuration needed?

**Comment by dc7290** [comment]
@samuel-2018 

Thank you!!!

> Is it possible to use this package with 'next/future/image'? Is there any different configuration needed?

It is not currently supported.
However, according to the Next.js update information, `next/future/image` seems to be the primary focus, so we plan to follow suit and support it.
In the meantime, we have issued an Issue.#255

**Comment by dc7290** [comment]
@samuel-2018 

Support for `next/future/image` has been added in ver. 1.9.0!
Please try it out.

**Comment by wytzejan** [comment]
@dc7290 thank you for your reply and sorry for my late reponse. I've used the package in a project but the project was in a hurry so at the end I did not use the package. I have tried it again with the version 1.9.0 but unfortunately I still get the same notice. I think it is an error at my end somewhere. Nevertheless, I will keep the code as it is right now because it is already in production. Maybe I need the package in the future; thanks for you work!

@samuel-2018 thanks for the heads up. I checked again but I was using the normal next/image import back then. I hope you can enjoy the package with the next/future/image in the latest version.

**Comment by samuel-2018** [comment]
> @samuel-2018
> 
> Support for `next/future/image` has been added in ver. 1.9.0! Please try it out.

The 'future' version works. Thanks!
