### ISSUE TITLE
Add info to documentation regarding supported file type

### ISSUE THREAD

**Issue by samuel-2018** [dc7290/next-export-optimize-images#264]
When using this package, it appears that all files that import `Image` must be of type “`.jsx`”. (I got a build error when using images with a file of type “`.js`”.)

If the files must be of type “`.jsx`”, can you add that information to the documentation?

**Comment by dc7290** [comment]
@samuel-2018 

I tried it in my environment and it works even with a file type of `.js`.
Maybe there is another cause.

Can you share the error message?

**Comment by samuel-2018** [comment]
@dc7290 

The error in the VSC console when running `next dev`:

`Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

(There is a similar error when running `next build`.)

I did notice another factor this time. I had the `package.json` set to `"type": "module"` and `next.config.js` was using import and export.

If I switch the project back to the commonJS module system, then Image can be used in a file ending in `.js`.

Here are the relevant files that were causing the error:

```json
{
  "name": "image-test",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "export": "next export && next-export-optimize-images",
  },
  "dependencies": {
    "next": "12.3.1",
    "next-export-optimize-images": "^1.9.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sharp": "^0.31.1"
  },
  "devDependencies": {
    "eslint": "8.24.0",
    "eslint-config-next": "12.3.1"
  }
}
```


```js
// file next.config.js

/** @type {import('next').NextConfig} */

import withExportImages from 'next-export-optimize-images';

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    loader: 'custom',
  },
};

const exportImageOptions = { configPath: 'export-images.config.js' };

const finalConfig = withExportImages(nextConfig, exportImageOptions);

export default finalConfig;
```

```js
// file export-images.config.js

/**
 * @type {import('next-export-optimize-images').Config}
 */
const config = {
  convertFormat: [
    ['png', 'webp'],
    ['jpg', 'avif'],
  ],
};

export default config;
```

```js
// file pages/post.js

import Image from 'next/image';
import React from 'react';

function Post() {
  return (
    <div>
      <Image
        src='/blogpost-image.jpg'
        alt='Blog Post Image'
        width={72}
        height={16}
      />
    </div>
  );
}

export default Post;
```
Did I miss some configuration that would allow for use of `Image` in `.js` files and still use ES6 import and export in `next.config.js`?

**Comment by dc7290** [comment]
@samuel-2018 

Thank you!

I don't know if this is the cause, but `next-export-optimize-images` does not currently support `type:module`.
Could you please remove `type:module` once and try again?

**Comment by samuel-2018** [comment]
> @samuel-2018
> 
> Thank you!
> 
> I don't know if this is the cause, but `next-export-optimize-images` does not currently support `type:module`. Could you please remove `type:module` once and try again?

That clarifies things. Thank you!

Yes, `Image` works in both `.js `and `.jsx` files when using the commonJS module system (no `"type": "module`" in the `package.json` file).
