### ISSUE TITLE
Downloads can fail from filenames being too long

### ISSUE THREAD

**Issue by YaBoiBurner** [dc7290/next-export-optimize-images#309]
**Describe the bug**
When downloading external images, next-export-optimize-images can try to save images to files with names longer than what the file system allows for. This causes the whole program to fail.
Since URL Search parameters are included in the output filename, this can just happen from having several search parameters.

Most file systems seem to limit things to 255 characters or bytes (ex. btrfs does 255 bytes), so that would probably be a fine length limit.

**To Reproduce**
1. Add an image with a really long filename to a project
2. Build
3. Export
4. run `next-export-optimize-images`

**Expected behavior**
The images are downloaded, and the export continues

**Screenshots**
![image](https://user-images.githubusercontent.com/10004812/202381384-956017d4-3a43-4767-883a-a3010dc481aa.png)

**Desktop**
 - OS: Linux

**Comment by Gp2mv3** [comment]
It's funny, I'm struggling with the exact same issue with images from Notion too for 2h.
I'm currently working on a PR to remove the part after "?" from the src attributes of the manifest file.
