### ISSUE TITLE
Crypto browserify included in bundle: Around 130kB of JS added

### ISSUE THREAD

**Issue by Gp2mv3** [dc7290/next-export-optimize-images#332]
**Describe the bug**
I think my fix in commit eae8c74b1d0a29cfa66fdbcf55f5a0bb838bdea1 increased the bundle size because of crypto-browserify.

**To Reproduce**
1. Analyze your bundle size with the package in version 1.9.1
2. Remove the "withExportImages" plugin
3. Re-analyze the bundle size

**Expected behavior**
There should be an impact but not that big. We don't need the full crypto package for a simple sha hash.

**Comment by dc7290** [comment]
Thanks for sharing the bundle size!

As for my earlier commit, it turns out that it was not resolved.
(On the contrary, it turns out that `fs-extra` is also included in the client bundle😇)
So, fundamentally, I felt that SWC needs to be able to remove the code used only on the server side.

**Comment by dc7290** [comment]
https://github.com/vercel/next.js/issues/36514

**Comment by dc7290** [comment]
@Gp2mv3 

For all the above reasons, please create a PR using hashCode!
Thanks!!
