### ISSUE TITLE
site won't load images after export when export-images.config.js is not default

### ISSUE THREAD

**Issue by airfortech** [dc7290/next-export-optimize-images#385]
Node: v18.13.0
Next: 13.1.2
next-export-optimize-images: 2.0.0

1. set something in export-images.config.js, fe.

```js
/**
 * @type {import('next-export-optimize-images').Config}
 */
const config = {
  convertFormat: [
    ["png", "webp"],
    ["jpg", "avif"],
  ],
// or
  filenameGenerator: ({ path, name, width, quality, extension }) =>
    `${path}/${width}/${quality}/${name}.${extension}`,
};

module.exports = config;
```

2. Run ```"export": "next build && next export && next-export-optimize-images"```
3. Run site via f.e. liveserver
4. Check source of html file with images. `srcSet` is ok at this point
5. Open devtools of same site with same images. `srcSet` are different so images images won't load when `png` was converted to `webp` ot `filenameGenerator` is custom.

**Comment by airfortech** [comment]
It seams it works with `next/image` but won't with `next/legacy/image`

**Comment by jason-dark** [comment]
I had the exact same problem. I found a fix when using the `convertFormat` option alone. However I am still unable to resolve this when creating custom file names using the `filenameGenerator` option.

I deleted:

1. .next directory
2. build output directory
3. node_modules/.cache

Then re-exported and deployed my site and it was fixed. Again just to clarify, this only works when setting a custom `convertFormat` value, using `filenameGenerator` is still broken for me.

**Comment by dc7290** [comment]
Thank you both!

First of all, I found out that there seems to be one problem.
It is that when I edit `export-images.config.js` and build again, the edits are sometimes not reflected.
This is probably due to the fact that Next.js has not been added to the dependency on Webpack used internally.

Apart from the above problem, I see that there is another issue where `convertFormat` and `filenameGenerator` do not work properly when used together.
I couldn't reproduce this one in my environment, so if you could share a minimally configured project, that would be great!

Thanks!

**Comment by dc7290** [comment]
> First of all, I found out that there seems to be one problem.
> It is that when I edit export-images.config.js and build again, the edits are sometimes not reflected.
> This is probably due to the fact that Next.js has not been added to the dependency on Webpack used internally.

This problem didn't seem to occur, so please go through with it.

**Comment by dc7290** [comment]
> Or not really. When i have main index page with images and other page, f.e. about, images loads on start but when i navigate to /about then back to /index, urls to images in devtools are incorrect and won't load. After refresh all is fine again. Navigate to /about and back, still same problem.

It's true that when I transition to a new page, the original extension is still there...
I'll check it out.

**Comment by dc7290** [comment]
I've done a lot of research, and I've come to the conclusion that

> I deleted:
> 
> .next directory
> build output directory
> node_modules/.cache

Doing this seems to solve everything.

I think the root cause is that the changes in `export-images.config.js` are not reflected properly in the client JavaScript that Next.js generates.

**Comment by airfortech** [comment]
@dc7290

example if you still need one:
https://github.com/airfortech/next.js-learning-blog

**Comment by airfortech** [comment]
> Doing this seems to solve everything.

It works but images caching is not working anymore for this workaround.

**Comment by jason-dark** [comment]
@dc7290 I believe this problem stems from using the **same remote image on multiple pages** in a Nextjs site. The docs state that an image filename must be unique, but when using a custom  filename generator it can be hard to achieve this.

I made a demo repo [here](https://github.com/jason-dark/duplicate-image-demo). If you follow the readme instructions to run it you can see the problem in action.

To be clear, I know the next-export-optimize-images config in this repo is causing the issue. But it's an example that demonstrates the issue and I believe this is a real world use case to solve for SEO reasons (as documented further in my PR [here](https://github.com/dc7290/next-export-optimize-images/pull/411)).

**Comment by airfortech** [comment]
> I made a demo repo [here](https://github.com/jason-dark/duplicate-image-demo). If you follow the readme instructions to run it you can see the problem in action.

For me your example works.

**Comment by jason-dark** [comment]
> 

Are you running it in dev or running a prod export?

**Comment by airfortech** [comment]
> Are you running it in dev or running a prod export?

git clone <your project>
npm install
npm run export
npx http-server out
