### ISSUE TITLE
Is it possible to exclude some images from optimization?

### ISSUE THREAD

**Issue by jason-dark** [dc7290/next-export-optimize-images#402]
**Is your feature request related to a problem? Please describe.**
In my Nextjs application some images are webp animations. Once the optimisation process has run, these are rendered as static images which are not animated. I would like to disable optimisation on just these images.

**Describe the solution you'd like**
A way to exclude images from optimisation on an individual basis, or failing that a way to entirely exclude a file type e.g. webp.

**Describe alternatives you've considered**
I have tried a variety of webp configurations in `sharpOptions` in `export-images.config.js` as per the [docs](https://next-export-optimize-images.vercel.app/docs/Configurations/basic-configuration#sharpoptions) but so far without success.

**Additional context**
Also wanted to say what an awesome lib this is. Thank you very much for your efforts.

**Comment by dc7290** [comment]
I think the following description will work!

```tsx
<Image
  // ~~~
  // other props
  // ~~~
  unoptimized ← Only images used in this component are not optimized
/>
```

And thanks again for your kind words!
