### ISSUE TITLE
`No images were found to optimize.` error message on Next.js 13.2.3

### ISSUE THREAD

**Issue by manspeterson** [dc7290/next-export-optimize-images#430]
Just tried the package for the first time and cannot get it to find/optimize any images. I've searched through all other issues and have tried using running it both with `next build && next-export-optimize-images` and `next build && next export && next-export-optimize-images`, both yielding the same error message. 

I'm on `Next.js 13.2.3` and are using the new `next/image` without any custom loaders.  The compiled image component do point to the correct paths, but cannot be resolved since the optimization part never gets run.

Reviewing the source code I guess it must have to do with that the `manifestJsonPath` cannot be resolved for some reason? Have something changed with the newest versions of `Next.js` or am I missing something?

**Comment by schwarzi33** [comment]
I have exactly the same problem with Next.JS version 13.3.1. Would appreciate any help 👍

**Comment by dc7290** [comment]
I could not reproduce the error in either version.

Is it possible to submit a code sample?

**Comment by dc7290** [comment]
@manspeterson 
This is a related issue to #106 ...

It's quite a difficult problem to solve.
In Next.js, the image size is determined when the component is rendered, which makes it difficult to optimize images correctly for components that are not evaluated at build time.

We are trying to address this issue through trial and error, but we are not making much progress...

In the meantime, I think the solution is to use opacity, etc., and have the element itself be rendered in such a way that the image is optimized.

**Comment by dc7290** [comment]
@manspeterson @schwarzi33 
Thank you for opening this issue!
Optimization is now available for dynamic URLs and components, and we have confirmed that it works with v3.0.5!

Please give it a try👍
