### ISSUE TITLE
List additional images to be optimized that are not rendered by a default next export

### ISSUE THREAD

**Issue by mauricedb** [dc7290/next-export-optimize-images#518]
Really cool package, thanks for creating :-)

**Is your feature request related to a problem? Please describe.**
In a number of cases I am dynamically creating the image URL to render because of different viewport sizes as well as other reasons like errors or AJAX requests. The result is that Next is not aware of all images when doing a `next export` and these are not written to the JSON file of images. And subsequently `next-export-optimize-images` is not aware of these images and the required optimization is not done.

**Describe the solution you'd like**
What would be very helpful is the capability to list all extra image files along with their size and quality so `next-export-optimize-images` know about them and creates the optimized versions anyway.

**Describe alternatives you've considered**
The only way to work around this limitation seems to be to create a dummy page and add a number of `<Image />` components there with all images. These would then be picked up and rendered. But that is a bit of a weird hack as that page is never supposed to be used and really should not exist.

**Comment by mauricedb** [comment]
I am certainly no expert in the source code here so what I am suggesting might not work at all.

But suppose you look for a JSON file with the same structure as `custom-optimized-images.nd.json` and if present add the files from there to the result of `processManifest()` here https://github.com/dc7290/next-export-optimize-images/blob/main/src/cli/index.ts#L142

That way they should be optimized together with the other files. 

To make it easier to use you might make the `width` and `quality` optional and determine the width from the actual file but that is probably not even needed.

**Comment by dc7290** [comment]
Thanks for the suggestion!

I think that method would work.
However, I also feel that it would be difficult to put together the necessary image information in a JSON file without knowing in advance what width of image `next/image` needs 🤔.

As a side note, here is a variation where `next/image` internally generates the image size.
- 1x,2x two ways
- Value of `deviceSizes` in `next.config.js`.
- The combined value of `deviceSizes` and `imageSizes` in `next.config.js`.

**Comment by dc7290** [comment]
@mauricedb 

Thank you for opening this issue!
Optimization is now available for dynamic URLs and components, and we have confirmed that it works with v3.0.5!

Please give it a try👍
