### ISSUE TITLE
Support Image use in server components

### ISSUE THREAD

**Issue by fazpu** [dc7290/next-export-optimize-images#527]
**Describe the bug**
- relevant dependencies:
```
"next": "13.4.2",
"react": "18.2.0",
"react-dom": "18.2.0"
"next-export-optimize-images": "^2.1.0",
```

- I'm using the new `app` directory router with its server components
- I'm using the current version of `next/image` (not the legacy one)

When I install the `next-export-optimize-images` and update the `next.config.js`, I'm getting this:

```
- error node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (1912:12) @ resolveModelToJSON
- error Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  <... src={{...}} alt=... unoptimized=... fill=... className=... priority=... loader={function} blurDataURL=...>
                                                                                      ^^^^^^^^^^
    at stringify (<anonymous>)
null

```

=> it seems the server component are not yet supported. Please, would it be possible to add the support?

Thank you for this project!

**Comment by dc7290** [comment]
Thanks for posting the problem!

I see.
AppRouter behavior is difficult :)

Our current policy is to investigate AppRouter and figure out how best to deal with the library as a whole.

Any information or advice would be greatly appreciated!

**Comment by dc7290** [comment]
@fazpu 

Thank you for opening this issue!
We have successfully completed AppRouter and confirmed that it works with v3.0.5!

Please give it a try👍
