### ISSUE TITLE
Optimise by serving multiple formats

### ISSUE THREAD

**Issue by HandyHat** [dc7290/next-export-optimize-images#544]
Thank you so much for the library!

**Is your feature request related to a problem? Please describe.**
I want to be able to serve next gen formats (webp, avif) to those on compatible browsers while allowing for a fallback to jpg/png for those on incompatible browsers.

**Describe the solution you'd like**
I provide a jpeg/png image. The library converts those images to webp/avif in the relevant sizes and serves all of the possible formats in all possible sizes, depending on what the browser supports.
Similar to the current convert formats functionality, but supporting multiple formats and serving optimised images from the original format too.

**Describe alternatives you've considered**
https://github.com/Niels-IO/next-image-export-optimizer supports this.

**Additional context**
The functionality I am looking for is the same that is available in next.js - see: https://nextjs.org/docs/app/api-reference/components/image#formats

**Comment by dc7290** [comment]
@HandyHat 
Hi.

At the moment it is possible to convert to webp or avif itself!
https://next-export-optimize-images.vercel.app/docs/Configurations/basic-configuration#convertformat

However, we are currently unable to provide support for various extensions that use browser functionality such as using the picture element 😭

https://github.com/Niels-IO/next-image-export-optimizer I thought that this library probably does not support the above picture element either…?

**Comment by dc7290** [comment]
Now that we have the groundwork in place to add this feature, we will proceed with this as well👍.

**Comment by HandyHat** [comment]
Thank you so much for looking into this and accepting this feature request!

> https://github.com/Niels-IO/next-image-export-optimizer I thought that this library probably does not support the above picture element either…?

`next-image-export-optimizer` does not use the picture element but instead uses a data image to check which formats are supported by the browser, and then serves images of the right format in an srcset

**Comment by knemerzitski** [comment]
I opened PR #667 that enables serving images in multiple formats. This is also directed at #653.

It adds a new config.
```js
const config = {
  generateFormats: ['jpg'],
}
```


I created a [demo project](https://github.com/knemerzitski/next-export-optimize-images-picture-tag-demo) to show how multiple images can be served. 

Check [PictureImage.tsx](https://github.com/knemerzitski/next-export-optimize-images-picture-tag-demo/blob/main/src/components/PictureImage.tsx) component for details.

Essentially you can use `unstable_getImgProps` from `next/image` to create srcset for each source as long as the image is actually generated.
