### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by marcuslindfeldt** [dc7290/next-export-optimize-images#609]
**Describe the bug**
I get errors with the latest version in client components.
As soon as I add an "use client" block I get the following error:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ForwardRef(CustomImage)`.
```

This seems to have been introduced with version 3. It worked with version 2 and an older version of nextjs (13.4.1).
I'm running next: 13.4.8 but you can also see the same error with next: 13.4.9.

**To Reproduce**
1. Create a custom client component with `"use client"` at the top of the file
2. Import an image src
3. Add it to the the `next/image` component

**Expected behavior**
No error

**Comment by dc7290** [comment]
Can you tell me the version of `Next.js` and `next-export-optimize-images`?

**Comment by marcuslindfeldt** [comment]
As mentioned. Tried with both Next `13.4.8` and `13.4.9` with the latest version (`3.0.6`) of `next-export-optimize-images`

Downgrading to next `13.4.7` and `next-export-optimize-images` `3.0.5` works. So it must be something in the latest versions that are incompatible.

**Comment by marcuslindfeldt** [comment]
Also worth mentioning that I'm using `output: "export"`. Filest that might be of interest:

```
// next.config.js
const withExportImages = require("next-export-optimize-images");
const withNextIntl = require("next-intl/plugin")(
  "./i18n.ts"
);

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  reactStrictMode: true,
  swcMinify: true,
  optimizeFonts: false,
  experimental: {
    appDir: true,
  },
  compiler: {
    removeConsole: false,
  },
};

module.exports = withExportImages(withNextIntl(nextConfig));
```

```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "~/*": ["./*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "app/types/**/*.d.ts"
  ],
  "exclude": ["node_modules"]
}
```

**Comment by dc7290** [comment]
なるほど・・・

私が試した限りだと、エラーが出ないんですよね・・・
- Next.js 13.4.9

**Comment by dc7290** [comment]
I see...

As far as I've tried, I don't see any errors...
- Next.js 13.4.9
- next-export-optimize-images 3.0.6

Is there some condition...

If you don't mind, can you share it in a repository or something?
