### ISSUE TITLE
Does not export images in conditionally rendered components

### ISSUE THREAD

**Issue by dash-james** [dc7290/next-export-optimize-images#610]
**Describe the bug**
I've recently started using next-export-optimize-images, and have arrived at the issue that images in conditionally rendered components, such as a modal or different component view, do not export and gives me 404 error for any images that are meant to be in these types of components. It looks like the src and srcset are renamed, but the images are missing.

**To Reproduce**
1. Create a conditionally rendered component (e.g. using state)
2. Build app
3. Open relevant page
4. Toggle the component to be shown
5. Images give 404 error

**Expected behavior**
Images to be exported and optimised in conditionally rendered components. Not get a 404 error.

**Screenshots**
<img width="601" alt="Screenshot 2023-07-14 at 12 14 11" src="https://github.com/dc7290/next-export-optimize-images/assets/86954361/67537c19-1e52-440e-8891-725bb71aafd1">
<img width="840" alt="Screenshot 2023-07-14 at 12 08 29" src="https://github.com/dc7290/next-export-optimize-images/assets/86954361/677d1e61-35dd-4d6f-a5af-3469090215d2">
<img width="890" alt="Screenshot 2023-07-14 at 12 12 12" src="https://github.com/dc7290/next-export-optimize-images/assets/86954361/2384b07b-d5d0-41c6-bf8a-4626cb7e9d0a">

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Browser: Chrome
 - Version: 114.0.5735.198

**Comment by dc7290** [comment]
Try using the latest ver of next-export-optimize-images!
This one is now supported in 3.0 👍

**Comment by dash-james** [comment]
I've also been getting the issues 'Element type is invalid' and 'Does not work with output: export' - this is why I had to downgrade both Next.js and next-export-optimize-images...

**Comment by dc7290** [comment]
I see...

In my environment, "Element type is invalid" and "Does not work with output: export" do not appear...
- Next.js 13.4.9
- next-export-optimize-images 3.0.6

If you don't mind, could you please share your repositories, etc.?

**Comment by dash-james** [comment]
Unfortunately it is a private repo that I am unable to share - however I also tried a downgrade to `next 13.4.7` and `next-export-optimize-images 3.0.5`

However, now it does not seem to export images using the following in my `next.config.js`. Only images in the public directory...

<img width="1077" alt="Screenshot 2023-07-14 at 13 42 27" src="https://github.com/dc7290/next-export-optimize-images/assets/86954361/fb83912e-4dbf-485c-aaea-600d315fd2d8">

<img width="337" alt="Screenshot 2023-07-14 at 13 41 10" src="https://github.com/dc7290/next-export-optimize-images/assets/86954361/9d341be1-b3ba-4d91-b2f0-15441b58c5e6">

**Comment by dc7290** [comment]
外部画像に関しては、ビルド時に全てを検知するのは不可能なので明示的に記述する必要があります！
https://next-export-optimize-images.vercel.app/docs/Features/external-images

(やや面倒なのですが・・・)

**Comment by dash-james** [comment]
That really makes it difficult for me since they are all coming from Prismic as a dynamic source - which means they will be changing over time. e.g. between builds. They also have dynamically generated img url. This was working previously in v2.1.0

**Comment by dc7290** [comment]
A disruptive change was made in v3.0.0.
This is to ensure that image optimization is performed for components that are not detectable at build time, such as dynamically switching components like the first one you mentioned.

However, the change also affects external images.
Originally, only images that could be detected at build time were targeted, so external images could be detected as well.
However, in order to optimize for images that are not detected at build time and to ensure consistency of behavior, we have explicitly changed the description of images that are not locally available, such as external images.

**Comment by dc7290** [comment]
I can't do it yet, but what if we multiply it by the following?
```js
// export-images.config.js

module.exports = {
  remoteImages: async () => {
    // Image acquisition process
    const imageUrls = await getImageUrls()
    return imageUrls
  },
}
```

**Comment by dc7290** [comment]
Well, I can only say that it depends on the application...

Basically, it should be done in the same way as the process of retrieving content from the CMS.

**Comment by dash-james** [comment]
I'm trying to search through the cms, but it is looking quite difficult for me. Is there a way to include all remote urls (that match the `remotePatterns` from next.config.js) that are used in the `next/image` component?

**Comment by dash-james** [comment]
Oh wow that was quick!

**Comment by dc7290** [comment]
I'm not familiar with Prismic ...

Am I correct in getting the following?
https://prismic.io/docs/fetch-data-nextjs

**Comment by dash-james** [comment]
Yes that is usually how I get data from the pages, however I'm currently trying to fetch data using this since it is in the config [Fetch data vanilla javascript](https://prismic.io/docs/fetch-data-vanilla-javascript)

**Comment by dc7290** [comment]
If the data retrieval that is done at the point where the images are passed to `next/image` is also done in `export-images.config.js`, it would be possible to retrieve all the images used in the site!?

**Comment by dash-james** [comment]
Would it be possible to get the urls from within the `next-export-optimize-images/dist/components/image` component?

**Comment by dc7290** [comment]
I think it would be difficult because it would be difficult to get only at build time ...

**Comment by dash-james** [comment]
It would have to be retrieved at build time, since new images are often added to the CMS. The CMS update then requires a new build

**Comment by dc7290** [comment]
Perhaps you could do the following?
I am not familiar with Prismic so I am not sure it is perfect.

```jsx
// index.jsx

export default function Page() {
  const [data, setData] = useState()
  useEffect(() => {
    client.getAllByType('blog_post').then((results) => setData(results))
  }, [])

  return (
    <ul>
      {results.map((content) => (
        <li>
          // 
        </li>
      ))}
    </ul>
  )
}
```

```js
// exprot-images.config.js

module.exports = {
  remoteImages: async () => {
    const results = await client.getAllByType('blog_post')
    return results.map((result) => result.image.url)
  }
}
```

**Comment by dash-james** [comment]
Yes somewhat, however I have multiple pages with multiple images deeply nested

**Comment by dc7290** [comment]
I see.

By the way, why not get the images directly from Prismic?
Prismic seems to have image optimization, so it seems like a good idea to use that as well.

**Comment by dash-james** [comment]
I have tried, unfortunately it does not cache and reduces the speed as then we rely on Prismic servers (which are often slow, depending on the location)

**Comment by dc7290** [comment]
Perhaps if I use the picture tag and set the fm and w parameters manually, it might be somewhat faster.
While it is convenient to use parameters that automate that area, does it take some time until they are generated once?

**Comment by dash-james** [comment]
I've gotten this so far... when the same code is in a page it returns all images urls in an array. It does not seem to fetch the urls in the config file. I have now updated to `next@13.4.9` and `next-export-optimize-images@3.1.0`

```
import * as prismic from '@prismicio/client'

module.exports = {
  remoteImages: async () => {
    const repositoryName = '****'
    const accessToken = '****'
    const routes = [
      {
        type: 'home',
        path: '/',
      },
      {
        type: 'services',
        path: '/services',
      },
      {
        type: 'service',
        path: '/services/:uid',
      },
      {
        type: 'work',
        path: '/work',
      },
      {
        type: 'case_studies',
        path: '/case-studies',
      },
      {
        type: 'case_study',
        path: '/case-studies/:uid',
      },
      {
        type: 'about',
        path: '/about',
      },
      {
        type: 'contact',
        path: '/contact',
      },
    ]
    const client = prismic.createClient(repositoryName, { routes, accessToken })

    let images = []
    function searchForImages(jsonArray) {
      jsonArray.forEach(function(jsonObj) {
        for (var key in jsonObj) {
          if (typeof jsonObj[key] === 'object') {
            searchForImages([jsonObj[key]]);
          } else if (typeof jsonObj[key] === 'string' && key !== 'meta_image') {
            if (jsonObj[key].includes('.jpg') || jsonObj[key].includes('.png')) {
              images.push(jsonObj[key])
            }
          }
        }
      });
    }

    const home = await client.getSingle('home')
    const services = await client.getSingle('services')
    const service = await client.getAllByType('service')
    const work_item = await client.getAllByType('work_item')
    const case_studies = await client.getSingle('case_studies')
    const case_study = await client.getAllByType('case_study')
    const about = await client.getSingle('about')
    
    searchForImages([home, services, service, work_item, case_studies, case_study, about])

    return images
  },
```

**Comment by dash-james** [comment]
I've added an async.. await to the searchForImages() function, still no luck in remoteImages picking these urls up and returning optimised assets. See updated comment above ^

I'm also getting an error for images in the public folder: "Error: ENOENT: no such file or directory". Not sure what to do about that either, I wasn't really planning on optimising the assets in the public directory since it is mainly small UI elements or favicon. Is there an option to turn this off or ignore certain files?
