### ISSUE TITLE
'basePath' config is ignored when running 'next dev'

### ISSUE THREAD

**Issue by petit-blaireau** [dc7290/next-export-optimize-images#623]
Hi,
I've ran into an issue when using both `next dev` and `basePath`.

**Describe the bug**
`basePath` config is ignored when using `next dev`

**To Reproduce**
1. Create an new next project and add next-export-optimize-images
2. Add `basePath: '/docs'` to both config files
2. Run `next dev` to run the dev server and navigate to http://localhost:3000/docs
3. The nextjs logo fails to load because `/docs/` is missing from the &lt;img&gt; url

![image](https://github.com/dc7290/next-export-optimize-images/assets/1893252/568a5b32-ed11-425d-8173-e350c7059a49)

The workaround is the remove the `basePath` config during development.

**Expected behavior**
Images should be displayed properly when using `next dev`

**Additional context**
next 13.4.10
next-export-optimize-images 3.1.0

**Comment by dc7290** [comment]
Thank you!
Please check here as we will proceed from here with the following Issue!

https://github.com/dc7290/next-export-optimize-images/issues/612
