### ISSUE TITLE
Images within client-side-only loaded components aren’t optimized

### ISSUE THREAD

**Issue by psirenny** [dc7290/next-export-optimize-images#63]
Images within client-side-only loaded components aren’t optimized. For example:

✅ This works

```ts
import dynamic from 'next/dynamic';
import type { NextPage } from 'next';
import ComponentWithImage from './ComponentWithImage';

export const Page: NextPage = () => (
  <main>
    <h1>Title</h1>
    <ComponentWithImage />
  </main>
);
```

❌ This doesn't work

```ts
import dynamic from 'next/dynamic';
import type { NextPage } from 'next';

const ClientSideComponentWithImage = dynamic(
  async () => await import('./ComponentWithImage'),
  { ssr: false }, // The problem
);

export const Page: NextPage = () => (
  <main>
    <h1>Title</h1>
    <ClientSideComponentWithImage />
  </main>
);
```

The **.next/custom-optimized-images.nd.json** manifest isn't populated with the dynamic images during `next build`.

**Comment by dc7290** [comment]
@psirenny 

First of all, thank you for opening the issue!

As to the main issue, I understand that you are unable to optimize images within a component that functions only on the client side.
Here's the thing, components that cannot be evaluated at build time cannot get information about the images to be optimized.
Therefore, the current specification does not allow optimization.

For your information, I would like to ask, when is an image component used within a component that functions only on the client side?

Thank you very much!

**Comment by psirenny** [comment]
> Here's the thing, components that cannot be evaluated at build time cannot get information about the images to be optimized.

Darn, I was hoping that wasn't the case.

I'm client-side loading components that aren't visible on initial page render. For example, content behind a model and content at the bottom of very long landing pages.

**Comment by dc7290** [comment]
I see.
It would certainly be nice to be able to use it that way.

Please give me some time to figure out how it works!
Also, if you have a specific design in mind, by all means, you can comment here or create a new feature request!

**Comment by reisi007** [comment]
@psirenny: How realistic is it to Regexp all ts(x) / js(x) files to look for the Image / have an option to optimize all images in a folder?
