### ISSUE TITLE
convertFormat option does not exchange fileNames in HTML 

### ISSUE THREAD

**Issue by schwarzi33** [dc7290/next-export-optimize-images#651]
**Description**

I am using the remoteImages async method to dynamically get the image url array from our CMS. Additionally i have configured the "convertFormat" option like:

`
convertFormat: [['png', 'webp']],
`

The download including the generation of the images are working quite fine and all the PNG files are converted into WEBP like this:
![image](https://github.com/dc7290/next-export-optimize-images/assets/91454885/2173915c-6c1a-4d90-8df9-1a1c50731360)

The problem now is that none of my images are shown on the page in production build cause the resulting image tag is still using the ".png" extension like this:

`
<img alt="" loading="lazy" decoding="async" data-nimg="fill" class="s-object-cover" style="position: absolute; height: 100%; width: 100%; inset: 0px;" sizes="100vw" srcset="/_next/static/chunks/images/image_2_386f0019ef_640.png 640w, /_next/static/chunks/images/image_2_386f0019ef_750.png 750w, /_next/static/chunks/images/image_2_386f0019ef_828.png 828w, /_next/static/chunks/images/image_2_386f0019ef_1080.png 1080w, /_next/static/chunks/images/image_2_386f0019ef_1200.png 1200w, /_next/static/chunks/images/image_2_386f0019ef_1920.png 1920w, /_next/static/chunks/images/image_2_386f0019ef_2048.png 2048w, /_next/static/chunks/images/image_2_386f0019ef_3840.png 3840w" src="/_next/static/chunks/images/image_2_386f0019ef_3840.png">
`

Is there anything I am may missing in the config or is the convertFormat option not working in combination with remoteImages?
I would be glad to have a solution for this!

Thanks for your help and BR

**Comment by schwarzi33** [comment]
After digging deeper into your source code I found out why it worked in v2.1.0 and not in v3.1.0:
In the getConfig() method you are checking the isBundleProcess and based on it you load the default or the own export-image.config.js:

![image](https://github.com/dc7290/next-export-optimize-images/assets/91454885/14b4c756-d65b-4d8d-9cf5-9783377064a8)

For the image generation (CLI) it's working cause isBundleProcess is false:
`
const config = getConfig_default({ isBundleProcess: false });
`

For the image loader itself it's true and therefore always the default config is used:
`
var config = getConfig_default({ isBundleProcess: true });
`

Would be awesome if you could provide a fix for this issue soon.

Thanks and BR

**Comment by dc7290** [comment]
Thank you!
Please check here as we will proceed from here with the following Issue!

https://github.com/dc7290/next-export-optimize-images/issues/612
