### ISSUE TITLE
e2e test check for files exist does not run

### ISSUE THREAD

**Issue by knemerzitski** [dc7290/next-export-optimize-images#666]
**Describe the bug**
File [index.test.ts line 28](https://github.com/dc7290/next-export-optimize-images/blob/main/__tests__/e2e/index.test.ts#L28) method toBeTruthy is not called to check if optimized files exists.

**Expected behavior**
Test runs and checks for existing optimized images.

**Comment by dc7290** [comment]
Thanks!
