### ISSUE TITLE
Add support for build cache

### ISSUE THREAD

**Issue by dash-james** [dc7290/next-export-optimize-images#692]
When building a larger project, it can be quite time consuming to optimise images for each build. Is there a way to implement build caching into this library in order to save time when generating static builds.

For example, Cloudflare now has build caching and all cached files are stored in the `.next/cache` folder. Is there any way to utilise this folder and store images that will be used across builds?

Thanks!

**Comment by dc7290** [comment]
Hi there!

It would be nice to have an option to change the directory where the images are cached!

**Comment by stavros-k** [comment]
Hello, is this a matter of providing a way to update this line here?
https://github.com/dc7290/next-export-optimize-images/blob/9027b63b31b15b4280b1e3c3a23cfb6060fbf964/src/cli/utils/cache.ts#L5

Or is there other things that need to be adapted in order to be able to change the cache dir?

Thanks!

**Comment by dc7290** [comment]
@stavros-k 
That is exactly what the line there is about!
We should be able to override this in the user's config, but it would be nice to have a contrib 👍.
