### ISSUE TITLE
"Successful optimization!" message shows even when there are errored assets

### ISSUE THREAD

**Issue by ben-z** [dc7290/next-export-optimize-images#706]
**Describe the bug**
"Successful optimization!" message shows even when there are errored assets. Here's a log snippet:

```
[Error: ENOENT: no such file or directory, open '/home/ben/Projects/infra-config/website/out/out/_{
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ben/Projects/infra-config/website/out/out/_next/static/media/goose-with-computer-da'
}
[Error: ENOENT: no such file or directory, open '/home/ben/Projects/infra-config/website/out/out/_{
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ben/Projects/infra-config/website/out/out/_next/static/media/goose-with-computer-da'
Cache assets: 192, NonCache assets: 0, Error assets: 128
[Error: ENOENT: no such file or directory, open '/home/ben/Projects/infra-config/website/out/out/_{
Successful optimization!
```

**To Reproduce**
1. Make image optimization fail. In my case, I set basePath in next.config.js but didn't set it in export-images.config.js
2. Observe a successful exit status

**Expected behavior**
Expected the process to return a nonzero exit status when there are error assets.

**Screenshots**
<img width="718" alt="image" src="https://github.com/dc7290/next-export-optimize-images/assets/5977478/bfce8940-f64f-4b04-9827-b2ccce78d29b">

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: N/A
 - Version: N/A

**Comment by dc7290** [comment]
Please share your configuration file.

**Comment by ben-z** [comment]
It's been too long. We've iterated too many iterations to continue investigating this. Please feel free to close this issue.
