### ISSUE TITLE
SVG is not a valid image file error with inline @svgr/webpack

### ISSUE THREAD

**Issue by huskyjp** [dc7290/next-export-optimize-images#755]
**Describe the bug**
SVG is not a valid image file error with inline using @svgr/webpack. Here is the error message
```
Error: Image import "@svg/Android.svg" is not a valid image file. The image may be corrupted or an unsupported format.
```

Should have fixed here https://github.com/dc7290/next-export-optimize-images/pull/658 but maybe happening again with the current next version?

**Expected behavior**
Should treat SVG as same as other formats

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Package versions**
- "next-export-optimize-images": "^3.2.0"
- "next": "^14.0.4"

**Comment by sven-ra** [comment]
did you find a solution for this?

**Comment by dc7290** [comment]
Do you have next.config.js to share?

The behaviour depends on the webpack extension settings.

**Comment by Emiliano-Bucci** [comment]
@dc7290 Hi! I'm facing this issue too, this is my next.config.mjs
```
import withExportImages from "next-export-optimize-images";

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "standalone",
  transpilePackages: ["@pandacss"],
  reactStrictMode: false,
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/i,
      issuer: /\.[jt]sx?$/,
      use: ["@svgr/webpack"],
    });
    return config;
  },
  images: {
    remotePatterns: [
      {
        hostname: "positano-booking-be-stage.s3.eu-west-1.amazonaws.com",
      },
    ],
  },
  logging: {
    fetches: {
      fullUrl: true,
    },
  },
};

export default withExportImages(nextConfig);
```
