### ISSUE TITLE
Possible to only statically export images and the rest of the code is not affected

### ISSUE THREAD

**Issue by petrusmatiros** [dc7290/next-export-optimize-images#780]
**Describe the bug**
I am trying to use the library to optimize images at build time. But using `output: 'export'` in the config leads to errors, since I need to use `getServerSideProps `in my code.

**Expected behavior**
Want to be able to only statically export images and not entire codebase

**Additional context**
I need to use getServerSideProps since I need to access `query`, `res `and `req `props

**Comment by abuu-u** [comment]
check https://github.com/dc7290/next-export-optimize-images/issues/105
