### ISSUE TITLE
Add `unoptimized` configuration option

### ISSUE THREAD

**Issue by beschler** [dc7290/next-export-optimize-images#808]
**Is your feature request related to a problem? Please describe.**
The [configuration options](https://next-export-optimize-images.vercel.app/docs/Configurations/basic-configuration) in the documentation do not list an option to **not optimize** an image (leave it untouched after it is downloaded).

**Describe the solution you'd like**
Add a new configuration option (e.g. titled `unoptimized`) with a `boolean` value, with a default of `false`. If set to `true`, the specified remote image(s) would be downloaded and stored as local static images, but no optimizations would be applied in the process.

**Describe alternatives you've considered**
I have considered using the `quality` value of `100`, but it's unclear to me if this still results in changes to the file after it's downloaded.

**Additional context**
My use case is as follows. I am looking to only download remote images from an AWS S3 bucket into static assets for a static site at build time. However, the images on the remote server are already optimized, and I would like an option to not perform any additional optimizations / transformations on the images when they are downloaded.

The similar library `next-image-export-optimizer` allows for the prop `unoptimized={true}`:
https://github.com/Niels-IO/next-image-export-optimizer/blob/master/README.md?plain=1#L185

**Comment by dc7290** [comment]
Can't you do this?

```jsx
<Image unoptimized>
```
