### ISSUE TITLE
images support optimization

### ISSUE THREAD

**Issue by torref** [dc7290/next-export-optimize-images#81]
Currently only local images are supported for optimization or any address of image supported ?

**Comment by dc7290** [comment]
@torref 

Thanks for asking!

Currently we only support local images.

As for external images, we are currently developing them.
The specification is to store optimized external images locally.
I will let you know here when this feature is released!

**Comment by hosnas** [comment]
@torref  thank you for your great work. 

Is there any estimation when we can have this feature?

**Comment by hosnas** [comment]
thank you for your great work @dc7290 .

Is there any estimation when we can have this feature?

**Comment by dc7290** [comment]
@hosnas 

I can't say for sure, but I hope to be able to make it public within the next 2.3 days.

**Comment by dc7290** [comment]
@hosnas 

I have released version 1.5.0 with a new feature about external images!

I will let you know when we add more information on how to use it to the documentation.

**Comment by dc7290** [comment]
@hosnas 

https://next-export-optimize-images.vercel.app/docs/Features/external-images

**Comment by dc7290** [comment]
@torref 

Thank you. 
I'm sorry, could you open a new problem?  

Please tell us a little more about the situation.  
Specifically, it includes a sample project presentation and the full text of the error message.
