### ISSUE TITLE
Hangs when there's an svg file

### ISSUE THREAD

**Issue by akinnee** [dc7290/next-export-optimize-images#82]
**Describe the bug**
If there's an svg, it just hangs and never finishes. The logs say it's not a supported file type. You should be able to just output the source file if it's not supported.

**To Reproduce**
`<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />`

**Expected behavior**
Should work just like the built-in server-side optimization.

**Screenshots**
<img width="733" alt="Screen Shot 2022-06-08 at 2 22 16 PM" src="https://user-images.githubusercontent.com/3019562/172689229-5eb21876-f76e-4ca2-a433-ed53a1a85b37.png">

**Desktop (please complete the following information):**
MacOS
Node v14.18.3

**Comment by dc7290** [comment]
@akinnee 

Thanks for reporting the issue!

Indeed, for unsupported images, it seems like a good idea to output them as they are.

When you say 'the built-in server-side optimization', do you mean the same as the Next.js image optimization server?
It seems that `svg` and `gif` are returned as is without optimization.
https://github.com/vercel/next.js/blob/canary/packages/next/server/image-optimizer.ts#L353
Please let me know if my perception is incorrect.

**Comment by akinnee** [comment]
> @akinnee 
> 
> Thanks for reporting the issue!
> 
> Indeed, for unsupported images, it seems like a good idea to output them as they are.
> 
> When you say 'the built-in server-side optimization', do you mean the same as the Next.js image optimization server?
> It seems that `svg` and `gif` are returned as is without optimization.
> https://github.com/vercel/next.js/blob/canary/packages/next/server/image-optimizer.ts#L353
> Please let me know if my perception is incorrect.

I think that's right! I meant that I'd expect the image component to function pretty much the same way with this as it does with the server image optimizer. Thanks.

**Comment by dc7290** [comment]
🎉 This issue is included in version v1.5.1.
