### ISSUE TITLE
How to import.  Does everyone need to be able to import under the name next/image?

### ISSUE THREAD

**Issue by dc7290** [dc7290/next-export-optimize-images#820]
Please give us your opinion!
I am wondering what should I do with the next major update?

## Subject

Currently, this library can be used in the same way as next/image as follows.

```jsx
import Image from 'next/image';

<Image src='/page/to/image.png' />
```

The reason why we originally did it this way was that we wanted users of this library to use it as smoothly as possible without being aware of the library, based on the idea that they only want to use the image optimisation of next/image in HTML export and not do anything special with it. 
However, with the updates to Next.js, it has become increasingly difficult to take this approach.
https://github.com/dc7290/next-export-optimize-images/issues/696 and https://github.com/dc7290/next-export-optimize-images/issues/796 are causing errors where useContext cannot be loaded.
This is a situation where the ReactServerComponents mechanism used by Next.js and the WebpackAlias mechanism are intertwined, causing a bug. (The original next/image component uses `use client` but is not loaded correctly.)

Other disadvantages are that next/image sometimes changes the module path internally, but we have to deal with that, and bugs caused by doing tricky things are gradually becoming bigger and bigger.

So, to cut to the chase, in the next major version we are thinking of changing it so that it will be used as follows.

```jsx
import Image from 'next-export-optimize-images';

<Image src='/page/to/image.png' />
```

I also intend to prepare codemods for a smoother transition.

**Comment by stavros-k** [comment]
I'm fun of keeping the same component name, with just different import path.
It is very easy to migrate from one to the other, by just search and replace.

If you used a different component name, the diff could end up bigger, as it might also shift other text around by a linter/formatter. 
With your proposal is a single line change per file that uses image.

Can't wait for this to complete so I can use it in my project!
Thanks!

**Comment by dc7290** [comment]
When the release is complete, comments will be automatically posted on this issue!

↓ Like this
https://github.com/dc7290/next-export-optimize-images/issues/653#issuecomment-1706540477

In addition, the change of the source code itself is trivial, so we plan to work on it this weekend along with the preparation of codemods.

The next release is aiming for the middle of April👍

**Comment by dc7290** [comment]
@stavros-k 
This has been released in v4!
As far as I can confirm, the previous problems have been fixed!

**Comment by stavros-k** [comment]
Thanks! seems to be working for me!
