### ISSUE TITLE
Export utils in order to be able to use the optimized image without using the component

### ISSUE THREAD

**Issue by stavros-k** [dc7290/next-export-optimize-images#822]
**Is your feature request related to a problem? Please describe.**

I want to use the optimized images in places other than the <Image/> component, for example:
As a tailwind class, (`bg-[url(getOptimizedImage("my-img")]`)
As an OG/Twitter Image in metadata.
A custom Image/Picture component. eg I want a picture component that will load not only different sized image, but a completely different image (content wise) on mobile vs desktop (eg veritcal vs horizontal)

**Describe the solution you'd like**
The util that generates the src for the Image component to be exported.

**Describe alternatives you've considered**
Figure out a post-processing technique, which I would like to avoid.

**Additional context**
Should be probably wait for this issue to be solved first https://github.com/dc7290/next-export-optimize-images/issues/820

**Comment by dc7290** [comment]
This looks very good!

I also understand the use case very well.

After the next major version upgrade, I will consider it positively!
