### ISSUE TITLE
Export external images with `export-images.config.js` returning error in Next.js

### ISSUE THREAD

**Issue by beschler** [dc7290/next-export-optimize-images#824]
**Describe the bug**
I am attempting to load [external images](https://next-export-optimize-images.vercel.app/docs/Features/external-images) in my `export-images.config.js` file, but I'm receiving an error:

```
./node_modules/pg/lib/connection-parameters.js:3:0
Module not found: Can't resolve 'dns'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/pg/lib/client.js
./node_modules/pg/lib/index.js
./node_modules/next-export-optimize-images/export-images.config.js
./node_modules/next-export-optimize-images/dist/components/image.js
./node_modules/next-export-optimize-images/image.js
```

**To Reproduce**
Here is the contents of my `export-images.config.js` file:

```js
require("dotenv").config();
const { Pool } = require("pg");
const { S3, GetObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");

const dbconnect = {
  host: process.env.DB_HOST,
  port: process.env.DB_PORT,
  user: process.env.DB_USER,
  database: process.env.DB_NAME,
};

const db = new Pool(dbconnect);

async function getStaticImages() {
  // get all photos from PostgreSQL database
  const client = await db.connect();
  const all_photos = await client.query(`SELECT filename FROM photos`);
  client.release();

  // connect to AWS S3 bucket
  const s3 = new S3({
    region: process.env.AWS_S3_REGION,
    credentials: {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    },
  });

  let photos = [];

  for (const row of all_photos.rows) {
    // get photo object from AWS S3 bucket
    const getObject = new GetObjectCommand({
      Bucket: process.env.NEXT_PUBLIC_AWS_S3_BUCKET,
      Key: row.filename,
    });

    // get pre-signed URL for AWS S3 bucket object
    const signedUrl = await getSignedUrl(s3, getObject, {
      expiresIn: 3600,
    });

    photos.push(signedUrl);
  }

  console.log(photos);

  return photos;
}

module.exports = {
  remoteImages: async () => {
    const staticImages = await getStaticImages();
    return staticImages;
  },
};
```

**Expected behavior**
When I copy this code and execute it using Node.js (`node test-export-images.js > output.txt`), the code executes as expected, and outputs a list of pre-signed URLs for every image from my database that are stored in my AWS S3 bucket.

However, running this in my Next.js app results in the error above.

A web search seems to indicate this has something to do with Javascript Promises, and that they're only allowed to run in a Node.js server environment, not in the browser. If this is the case, can you recommend a change to my `export-images.config.js` file?

**Screenshots**
![Screenshot 2024-04-02 at 8 47 05 PM](https://github.com/dc7290/next-export-optimize-images/assets/6172425/f099e4ce-b75d-4adc-a1c3-5e20d9ef30d9)

**Desktop (please complete the following information):**
 - Device: MacBook Pro 16-inch, 2023, M2 Pro
 - OS: macOS Ventura 13.6.5
 - Browser: Google Chrome
 - Version: 123.0.6312.87

**Additional context**
 - Next.js Version: 14.1.3

**Comment by dc7290** [comment]
Perhaps there is a library that is not available on the front-end side that is causing the problem.
Maybe running `export-images.config.js` beforehand to convert remoteImages to static values would solve this.
