### ISSUE TITLE
Library produces resized images, but not using them in the 'srcSet' attribute

### ISSUE THREAD

**Issue by jpomykala** [dc7290/next-export-optimize-images#826]
next-export-optimize-images: 3.3.0
next: 14.1.4
node: 21.7.3

This is probably more a question rather a bug. I've configured library according to the docs here: https://next-export-optimize-images.vercel.app/docs/getting-started and I didn't made any custom config to it.

I see that library created bunch of resized images and various formats (including webp). However, in the final output in places where I use `<Image/>` component from `next/image`:

```
<Image src="/landing/example.png"
               width={2260}
               height={1360}
               placeholder="blur"
               priority={true}
               alt="example"
               className="img-fluid mt-4"
        />  
```

I'm getting `img` tag looking like this:

```
<img 
alt="example" 
fetchpriority="high" 
width="2260" 
height="1360" 
decoding="async" 
data-nimg="1" 
class="img-fluid mt-4" 
style="color: transparent;" 
srcset="/_next/static/chunks/images/landing/example_3840.png 1x" 
src="/_next/static/chunks/images/landing/example_3840.png">
```

Now I'm wondering, shouldn't the library provide more links in `srcset` attribute, like:

```
/_next/static/chunks/images/landing/example_3840.png 3840w
/_next/static/chunks/images/landing/example-template-in-editor_1080.png 1080w
/_next/static/chunks/images/landing/example-template-in-editor_828.png 828w
```

In this example the original image size is 2260px by 1360px.

**Comment by jpomykala** [comment]
Thanks you for the answers. I've added `layout="responsive"` to the Image component and now `srcSets` are set correctly. 👍

**Comment by dc7290** [comment]
I see.
So you are using legecy/image👍.
