### ISSUE TITLE
Next.js cant find remotePatterns when I use withExportImages wrapper for nextConfig

### ISSUE THREAD

**Issue by h0lme3** [dc7290/next-export-optimize-images#885]
Hi

I want to apply to do image optimization for `local/internal` images but dont wanna apply image optimiztion for `remote/external` images.

I made custom image component for it so I will use `CustomNextImage` from `next-export-optimize-images/image` for `local/internal` images and 
I will use `NextImage` from `next/image` for `remote/external` images.

```typescript
// Image.tsx
import NextImage from "next/image";
import CustomNextImage from "next-export-optimize-images/image";

export default function Image({ optimize = true, ...props }) {
   return optimize ? <CustomNextImage {...props} /> : <NextImage {...props} />
}
```

```typescript
// test.tsx
import { Image } from "./Image"

export default function Test() {
   return (
       <>
              <Image optimize={false} src={`external/remote image src`} />
              <Image optimize={true} src={`internal/local image src`} />
       </>
   )
}
```

And edited nextjs.config file like the following:
```typescript
import withExportImages from "next-export-optimize-images";

const nextConfig = withExportImages({
  ...
   images: {
      remotePatterns: [
         { protocol: "https", hostname: "remote domain" },
         { protocol: "https", hostname: "raw.githubusercontent.com" },
       ],
   }
   ...
})
```

But I unfortunately got this issue even thou I already configured remote domain for remote images
![image](https://github.com/dc7290/next-export-optimize-images/assets/98631674/3519f4b8-e24b-42ce-82b1-904b3e79fc07)

Maybe I dont know how to configure properly with `next-export-optimize-images/image` - Can you help me with it?

When I cancel to add `withExportImages` wrapper for `nextConfig` it is just fine but I need to wrap it because I want to optimize local images by using `next-export-optimize-images`

Please help me - Thank you!!!

**Comment by dc7290** [comment]
It looks like I need to modify the Image component first as follows.

```
// Image.tsx
import NextImage from "next/image";
import CustomNextImage from "next-export-optimize-images/image";

export default function Image({ optimize = true, ...props }) {
   return optimize ? <CustomNextImage {...props} /> : <NextImage {...props} unoptimized />
}
```

Also, in that case, the remotePatterns setting is not necessary.
This setting is for applying the image optimisation of next/image to external images, so it is not necessary if you do not optimise external images as in this case.

These are Next.js usages and have nothing to do with this library.
