### ISSUE TITLE
Error loading "sharp" module during yarn build

### ISSUE THREAD

**Issue by jtwings** [dc7290/next-export-optimize-images#902]
When attempting to build the project using yarn build, the following error occurs:
`Error: Could not load the "sharp" module using the win32-x64 runtime`
**Steps to Reproduce:**
- Install `next-export-optimize-images` package.
- Run `yarn build` command.
**Expected Behavior:**
The project should build successfully without any errors related to the "sharp" module.
**Actual Behavior:**
Encountered an error indicating the inability to load the "sharp" module.
**Environment:**
- Node.js version: 20.9.0
- Operating System: Windows (win32-x64)
- Nextjs 14.2.3
- Project dependencies: next-export-optimize-images, sharp
**Additional Context:**
- The issue started occurring after installing and using the next-export-optimize-images package.
- The "sharp" module is installed via yarn add sharp@latest.
- The error message suggests possible solutions but none of them resolved the issue.

```
G:\web-v3\node_modules\sharp\lib\sharp.js:114
  throw new Error(help.join('\n'));
  ^

Error: Could not load the "sharp" module using the win32-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\sharp\lib\sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\sharp\lib\constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dc7290** [comment]
This appears to be a problem when using `sharp` and `yarn` (v1).
Run the following additional commands as per the error minutes, and then run.

```
yarn add sharp --ignore-engines
```

**Comment by jtwings** [comment]
I also tried this way:

`$ yarn add sharp --ignore-engines
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "C:\\Users\\Wings\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.3"] is trying to unpack in the same destination "C:\\Users\\Wings\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
warning "eslint-config-next > @typescript-eslint/parser@7.2.0" has incorrect peer dependency "eslint@^8.56.0".
warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > ts-api-utils@1.3.0" has unmet peer dependency "typescript@>=4.2.0".
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ sharp@0.33.4
info All dependencies
└─ sharp@0.33.4
Done in 4.44s.`

Then run `yarn build`

`G:\web-v3\node_modules\cli-progress\lib\formatter.js:1
const _stringWidth = require('string-width');
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module G:\puramu-web-v3\node_modules\string-width\index.js from G:\puramu-web-v3\node_modules\cli-progress\lib\formatter.js not supported.
Instead change the require of index.js in G:\puramu-web-v3\node_modules\cli-progress\lib\formatter.js to a dynamic import() which is available in all CommonJS modules.       
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\cli-progress\lib\formatter.js:1:22)
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\cli-progress\lib\generic-bar.js:3:20)
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\cli-progress\lib\single-bar.js:1:21)
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\cli-progress\cli-progress.js:1:20)
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\next-export-optimize-images\dist\cli.js:195:35)
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\next-export-optimize-images\bin\index.js:2:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Then run `yarn add cli-progress`

`$ yarn add cli-progress
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "C:\\Users\\Wings\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.3"] is trying to unpack in the same destination "C:\\Users\\Wings\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning sharp@0.33.4: The engine "libvips" appears to be invalid.
warning @img/sharp-darwin-arm64@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-darwin-arm64@0.33.4: The engine "glibc" appears to be invalid.
warning @img/sharp-darwin-x64@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-darwin-x64@0.33.4: The engine "glibc" appears to be invalid.
warning @img/sharp-libvips-darwin-arm64@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-darwin-arm64@1.0.2: The engine "macos" appears to be invalid.
warning @img/sharp-libvips-darwin-x64@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-darwin-x64@1.0.2: The engine "macos" appears to be invalid.
warning @img/sharp-libvips-linux-arm@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-linux-arm@1.0.2: The engine "glibc" appears to be invalid.
warning @img/sharp-libvips-linux-arm64@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-linux-arm64@1.0.2: The engine "glibc" appears to be invalid.
warning @img/sharp-libvips-linux-s390x@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-linux-s390x@1.0.2: The engine "glibc" appears to be invalid.
warning @img/sharp-libvips-linux-x64@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-linux-x64@1.0.2: The engine "glibc" appears to be invalid.
warning @img/sharp-libvips-linuxmusl-arm64@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-linuxmusl-arm64@1.0.2: The engine "musl" appears to be invalid.
warning @img/sharp-libvips-linuxmusl-x64@1.0.2: The engine "pnpm" appears to be invalid.
warning @img/sharp-libvips-linuxmusl-x64@1.0.2: The engine "musl" appears to be invalid.
warning @img/sharp-linux-arm@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-linux-arm@0.33.4: The engine "glibc" appears to be invalid.
warning @img/sharp-linux-arm64@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-linux-arm64@0.33.4: The engine "glibc" appears to be invalid.
warning @img/sharp-linux-s390x@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-linux-s390x@0.33.4: The engine "glibc" appears to be invalid.
warning @img/sharp-linux-x64@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-linux-x64@0.33.4: The engine "glibc" appears to be invalid.
warning @img/sharp-linuxmusl-arm64@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-linuxmusl-arm64@0.33.4: The engine "musl" appears to be invalid.
warning @img/sharp-linuxmusl-x64@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-linuxmusl-x64@0.33.4: The engine "musl" appears to be invalid.
warning @img/sharp-wasm32@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-win32-ia32@0.33.4: The engine "pnpm" appears to be invalid.
warning @img/sharp-win32-x64@0.33.4: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning "eslint-config-next > @typescript-eslint/parser@7.2.0" has incorrect peer dependency "eslint@^8.56.0".
warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > ts-api-utils@1.3.0" has unmet peer dependency "typescript@>=4.2.0".
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ cli-progress@3.12.0
info All dependencies
└─ cli-progress@3.12.0
Done in 3.62s.`

Then run `yarn build` again it will return the first problem

`G:\web-v3\node_modules\sharp\lib\sharp.js:114
  throw new Error(help.join('\n'));
  ^

Error: Could not load the "sharp" module using the win32-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\sharp\lib\sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (G:\puramu-web-v3\node_modules\sharp\lib\constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`


**I just realized there's another important issue. I haven't used the RemoteImage component for remote image yet** I'm wondering if that's what's causing this error

**Comment by dc7290** [comment]
Errors related to `string-width` can be avoided by

`package.json`
```
~~~
  "resolutions": {
    "string-width": "4.2.3"
  }
~~~
```

I think the error again after doing `yarn add cli-progress` is because the installation of SHARP has been redone.
So I think the problem will be solved if you work in the following order!

1. add resolutions to package.json.
2. install sharp.
```
yarn add sharp --ignore-engines
```
3. build.
```
yarn build
```

---

The RemoteImage component is not relevant in this case.
However, I think it is easier to handle external images if you use this, so I recommend it!👍

**Comment by jtwings** [comment]
Thank you very much, it work like a charm.
