### ISSUE TITLE
getOptimizedImageProps not being exported

### ISSUE THREAD

**Issue by jac00000b** [dc7290/next-export-optimize-images#981]
**Describe the bug**
`getOptimizedImageProps` isn't being exported by the package

**To Reproduce**
1. Try to `import { getOptimizedImageProps } from "next-export-optimize-images/image";`
2. Typescript throws `Module '"next-export-optimize-images/image"' has no exported member 'getOptimizedImageProps'.`

**Expected behavior**
Return `getOptimizedImageProps` function

**Additional context**
I was following https://next-export-optimize-images.vercel.app/docs/Features/get-props

**Comment by dc7290** [comment]
Thanks for the report!
Can you provide a reproducible repository or a sample in CodeSandbox?

**Comment by CEM-Christian** [comment]
I'm having the same issue and created a CodeSandbox here: [https://codesandbox.io/p/devbox/c3cf2g](https://codesandbox.io/p/devbox/c3cf2g)
It just uses the NextJS default template, and attempts to define a component 'ImageWithArtDirection'

**Comment by dc7290** [comment]
Upon investigation, it was discovered that the library code does not include the d.ts file.
https://www.npmjs.com/package/next-export-optimize-images?activeTab=code

I am looking into the reason.

**Comment by CEM-Christian** [comment]
I've updated to the latest version but it appears the issue is still present?

Updated codebox: https://codesandbox.io/p/devbox/vibrant-violet-km42sy

**Comment by dc7290** [comment]
tsupのバグでまだ引き続き発生しているようですね。。。
もう一度修正してみます。

**Comment by dc7290** [comment]
@CEM-Christian 
I've confirmed that it has been fixed in v4.6.1!
